# Generated by Django 4.2.6 on 2023-10-16 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shelving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_of_the_shelf', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('quantity_products_in_stock', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('child_shelving', models.ManyToManyField(blank=True, related_name='child_shelving', to='test_app.shelving')),
                ('shelving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelving', to='test_app.shelving')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_products_in_order', models.PositiveSmallIntegerField(default=1)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_for_order', to='test_app.product')),
            ],
        ),
    ]
