# Generated by Django 4.2.6 on 2023-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_product_quantity_products_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelving',
            name='additional_shelving',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
