# Generated by Django 4.2.6 on 2023-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_shelving_additional_shelving'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildShelving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_of_the_child_shelf', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='shelving',
            name='additional_shelving',
        ),
        migrations.AddField(
            model_name='product',
            name='child_shelving',
            field=models.ManyToManyField(blank=True, to='test_app.childshelving'),
        ),
    ]
